[package]
name = "dec-number"
version = "0.0.4"
authors = ["senees <code@senees.de>"]
description = "Decimal Floating Point Arithmetic for Rust"
documentation = "https://docs.rs/dec-number"
repository = "https://github.com/senees/decNumber.rs.git"
license = "MIT"
edition = "2021"

[dependencies]
